### ISSUE TITLE
gitter.im broken link image in readme

### ISSUE THREAD

**Issue by ashwini0529** [coala/coala-html#113]
In https://github.com/coala/coala-html#getting-involved
the gitter logo needs a fix.
<img width="933" alt="screen shot 2017-02-08 at 2 23 29 am" src="https://cloud.githubusercontent.com/assets/8419333/22711024/a1888160-eda5-11e6-8d57-03c6c9a31c3d.png">

**Comment by Mariatta** [comment]
Looks fine for me :thinking: 

![screen shot 2017-02-07 at 1 46 43 pm](https://cloud.githubusercontent.com/assets/5844587/22713087/e5402350-ed3b-11e6-84b8-4d705069e1bf.png)

**Comment by ashwini0529** [comment]
How can that happen? 😕

**Comment by Makman2** [comment]
maybe you have some proxy?

**Comment by Mariatta** [comment]
Closing since this doesn't appear to be coala's problem.

**Comment by ashwini0529** [comment]
I tried it on some other network as well. Same issue

**Comment by Makman2** [comment]
I can see the badge too. If it's not a proxy, I don't know what to try else :/

**Comment by meetmangukiya** [comment]
Works for me as well

**Comment by meetmangukiya** [comment]
Use inspect elements and go to network section, you'll probably find what is wrong

**Comment by ashwini0529** [comment]
<img width="505" alt="screen shot 2017-02-08 at 6 13 51 pm" src="https://cloud.githubusercontent.com/assets/8419333/22737735/635a8610-ee2a-11e6-96b2-855c92c84823.png">
