### ISSUE TITLE
Upgrade bower dependencies in bower.json

### ISSUE THREAD

**Issue by sahilarora535** [coala/coala-html#115]
The dependencies in bower.json are outdated and should be upgraded.

**Comment by jayvdb** [comment]
Please be more detailed in your issue description, explaining a real problem.

**Comment by sahilarora535** [comment]
@jayvdb `coala-html` uses very old versions of `angular` and other plugins, which are now being outdated. Hence I thought it would be great if the dependencies could be updated to the latest stable versions so that adding dependencies to `angular` becomes easy. Please check [this comment](https://github.com/coala/coala-html/pull/116#discussion_r105405277) and give some suggestions on how I should improve on this.

**Comment by sahilarora535** [comment]
Closing as suggested by @jayvdb  in https://github.com/coala/coala-html/pull/116#discussion_r105411982
