### ISSUE TITLE
UI Mockup of Search and Filtering Functionality

### ISSUE THREAD

**Issue by hemangsk** [coala/coala-html#120]
Heyo everyone! For phase 3 of GSoC, I will be working on UI enhancement of coala-html. That is adding search functionality, and filtering on the basis of several parameters.

What I've been thinking is that the search bar should look like the one for the coala Online module as that will give a feel of consistency throughout. 

For result filtering, these parameters can be used,
- Severity
- Bears
- Files

So, 
![screen shot 2017-03-18 at 12 59 11 am](https://cloud.githubusercontent.com/assets/13018570/26322816/3c0ca16c-3f4a-11e7-88fd-b21475d8eddc.png)

It'd be really great if you share your thoughts.

**Comment by sils** [comment]
# Filter by Files

I don't think this should be a dropdown, rather a textbox which live filters. TBH I think this can be removed fully in favour of the "omni search bar above"; as for the other filters, I'd go with the chip style that we also have for bear seletion on https://coala.io/#!/tryonline

# Search Bar

- should have same width as results IMO

# Overall design

Can we use the coalaCSS? Also IMO we should use the same design which we're using for the other websites.

# Missing Bits

I think the logs and files view are also important to consider.

**Comment by hemangsk** [comment]
Sounds good, making the new UI with the changes.

> Can we use the coalaCSS? Also IMO we should use the same design which we're using for the other websites.

totally, sounds like a plan. And if this search bar with coala icon in the button looks good, then we can add this search bar in coalaCSS. Use it couple of places like coala Online module. It can generally serve the purpose wherever a button is required to __run coala__.

> I think the logs and files view are also important to consider.

on it 🚀

**Comment by hemangsk** [comment]
### Results View with omni search bar & filters for bears
![screen shot 2017-05-28 at 1 38 06 am](https://cloud.githubusercontent.com/assets/13018570/26524112/5e64e184-4346-11e7-8e70-218767e96dd4.png)


### Log View
- Cards from coalaCSS for logs
![screencapture-0-0-0-0-8000-1495915387396](https://cloud.githubusercontent.com/assets/13018570/26524083/a53774ba-4345-11e7-86c0-db453a01136e.png)


### Files View 
- Content Focussed 
- No borders
- Relevant icons beingshown next to the file name
![screencapture-coala-github-io-coala-html-1495915311863](https://cloud.githubusercontent.com/assets/13018570/26524087/c4e2b4e6-4345-11e7-8f58-507b5da49e0c.png)

**Comment by hemangsk** [comment]
Home View
- Consistent with coala.io
- Transparent background in navbar
- Search, Tab Navigation and other components powered by coalaCSS

![screen shot 2017-05-29 at 3 32 12 pm](https://cloud.githubusercontent.com/assets/13018570/26546025/9c81f93a-4485-11e7-80d9-ac59f92ca7c8.png)

**Comment by hemangsk** [comment]
Completed in https://github.com/coala/coala-html/pull/121
