### ISSUE TITLE
tutorial link in README.rst not working

### ISSUE THREAD

**Issue by yashovardhanagrawal** [coala/coala-html#134]
The tutorial link in README.md is not working and showing a 404 error.

**Comment by Ananthavijay** [comment]
I think you are referring to this link http://coala.readthedocs.io/en/latest/Getting_Involved/README.html which is under the About section..So what link should be there?

**Comment by monsij** [comment]
@Makman2 Is this issue still valid. If it is , please assign it to me and kindly mention the file to be edited.

**Comment by Makman2** [comment]
Please read the issue ;)

**Comment by monsij** [comment]
But the file README.md does not exists.There is a similar file README.md only

**Comment by Ananthavijay** [comment]
I think the title should be changed from "tutorial link in README.md not working" to "tutorial link in README.rst not working "

**Comment by Makman2** [comment]
@monsij I mean it's the readme, regardless of its ending ;)
