### ISSUE TITLE
coalahtml/tree.py: Increase readability

### ISSUE THREAD

**Issue by Uran198** [coala/coala-html#55]
In https://github.com/coala-analyzer/coala-html/blob/master/coalahtml/tree.py#L40 
`if not prev_node.child.get(new_node.name, None):` is better to change to 
`if new_node.name not in prev_node.child:`. It'll be easier to read and it's more correct, as `None` or `False` can be key in general.

**Comment by tushar-rishav** [comment]
Shall we mark it as newcomer?

**Comment by AbdealiJK** [comment]
@yashhsethiya Interested in making a PR for this ?

**Comment by yashhsethiya** [comment]
Yeah Sure @AbdealiJK

**Comment by RaiVaibhav** [comment]
@yashhsethiya  are you still working on this

**Comment by adtac** [comment]
It has been over a year now. Unassigning @yashhsethiya.

**Comment by sotanishy** [comment]
Can I take up this issue?
