### ISSUE TITLE
Please take me out of the mentioning list for the automatic issue reply :) 

### ISSUE THREAD

**Issue by Makman2** [coala/coala-html#66]

**Comment by hypothesist** [comment]
Ah , the irony :P

**Comment by sils1297** [comment]
so there's a bug in gitmate that doesn't allow me to configure the repo anymore with the UI because of some token expiration and me getting a new token... not sure that can be fixed easily in the prototype.

**Comment by sils1297** [comment]
auto replies shouldn't happen anymore

**Comment by Makman2** [comment]
yey :D
