### ISSUE TITLE
setup.py: Update meta data

### ISSUE THREAD

**Issue by tushar-rishav** [coala/coala-html#72]
Meta data needs to be updated. Refer https://pypi.python.org/pypi/coala-html

**Comment by guptavaasu** [comment]
assign me this please!

**Comment by Adrianzatreanu** [comment]
unassigning due to inactivity

**Comment by OctavianGuzu** [comment]
Assign me to this!

**Comment by sils** [comment]
see other issue, you're already assigned to another issue

**Comment by Mixih** [comment]
Hello, I'd like to be assigned. Also, can I have some more info? I not quite sure what needs to be updated.

**Comment by sils** [comment]
Hi! Welcome to our community and thank you for your interest!

I have sent you an invitation to join our community. This is needed so we can coordinate tasks with you and make sure no two persons are working on the same thing. If you can't find the mail, you should be able to join us at http://github.com/coala-analyzer/!

> Hint: if you're proud to be part of the team, you can make your membership public at https://github.com/orgs/coala/people

We'd love to be able to help you when problems occur. Just join us on [our gitter channel](https://coala.io/chat) and tell us about them :)

**Comment by arsalansaad** [comment]
i would like to work on this. I would also like to have some more info.

**Comment by sils1297** [comment]
@tushar-rishav what is needed hefe?

**Comment by arsalansaad** [comment]
@tushar-rishav what is to be updated in the metadata

**Comment by tushar-rishav** [comment]
Hey folks,

When I created this issue, some of the additional metadata at PyPi were
being added manually. To fix this, I just had to add those categories in
setup.py file.
Seemingly, the issue has been solved now.
@sils We may close this issue.

**Comment by sils** [comment]
ok
