### ISSUE TITLE
Show diffs in results view

### ISSUE THREAD

**Issue by sils** [coala/coala-html#97]
We already show them inline when viewing the file, why aren't we using the same code for both the results and the file view?

**Comment by SarthakNijhawan** [comment]
can I get assigned to this issue ?

**Comment by sils** [comment]
@SarthakNijhawan it's yours :)

**Comment by SarthakNijhawan** [comment]
@sils Thnks

**Comment by SarthakNijhawan** [comment]
@sils is there sumthin more which I can refer to get into the details of what exactly are we expecting outta it ?

**Comment by sils** [comment]
The description should tell you what needs to be done here, consider taking
something simpler maybe?

**Comment by SarthakNijhawan** [comment]
@sils I got it , actually !! 😛 I'll work on it .

**Comment by yashovardhanagrawal** [comment]
can I work on this issue?

**Comment by yashovardhanagrawal** [comment]
asking corobo to assign me this issue

**Comment by yashovardhanagrawal** [comment]
@sils I think this issue is no longer needed as diffs are already being showed in results view

**Comment by yashovardhanagrawal** [comment]
refer to https://github.com/coala/coala-html/commit/8e00f65a1016ffec1d92e91b82bf285d7f522997

**Comment by hemangsk** [comment]
Right, this is done via https://github.com/coala/coala-html/pull/121
